/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import App.Controller;
import Backup.BackupPreset;
import Backup.BackupPreset.PresetType;
import Backup.BackupPresets.SimplePreset;
import Models.BackupModel;
import UiHelpers.BackupPresetComboBoxRenderer;
import UiHelpers.DbTableListCellRenderer;
import UiHelpers.UiLib;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Rectangle;
import java.awt.geom.Line2D;
import java.util.Arrays;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import App.Config;

public class BackupView extends javax.swing.JPanel {

    private final Controller controller;
    private final BackupModel model;

    /**
     * Array consisting of all the tables in the database. The tables can be
     * loaded from the model.
     */
    private String[] tables;

    private List<BackupPreset> presets;

    public enum SWITCH_TYPE {
        TO_LEFT,
        TO_RIGHT;
    }

    /**
     * Creates new form BackupView
     *
     * @param controller The controller used to initialize this view.
     * @param model The model used to initialize this view.
     */
    public BackupView(Controller controller, BackupModel model) {
        initComponents();
        initComponentsExtra();
        this.controller = controller;
        this.model = model;
        loadData(false);
        loadBackupPresetsIntoView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        presetPanel = new javax.swing.JPanel();
        loadPresetButton = new javax.swing.JButton();
        presetPicker = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        backupPresetDescription = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        tablePanel = new javax.swing.JPanel();
        createBackupButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        excludedTablesList = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        includedTablesList = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        reloadTablesButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(15, 124, 160));
        setPreferredSize(new java.awt.Dimension(967, 479));

        loadPresetButton.setText("Load Preset");
        loadPresetButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onLoadPresetButtonClicked(evt);
            }
        });

        presetPicker.setBorder(null);
        presetPicker.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                presetPickerPropertyChange(evt);
            }
        });

        jScrollPane1.setBorder(null);

        backupPresetDescription.setEditable(false);
        backupPresetDescription.setBorder(null);
        jScrollPane1.setViewportView(backupPresetDescription);

        jLabel1.setFont(UiLib.getTitleFont());
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Backup Presets");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout presetPanelLayout = new javax.swing.GroupLayout(presetPanel);
        presetPanel.setLayout(presetPanelLayout);
        presetPanelLayout.setHorizontalGroup(
            presetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(presetPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(presetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(loadPresetButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(presetPicker, 0, 273, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(presetPanelLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        presetPanelLayout.setVerticalGroup(
            presetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, presetPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(presetPicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loadPresetButton)
                .addGap(14, 14, 14))
        );

        createBackupButton.setText("Create Backup");

        jScrollPane2.setBorder(UiLib.createDefaultLineBorder());
        jScrollPane2.setOpaque(false);

        excludedTablesList.setBackground(Config.Colors.APPLICATION_DEFAULT_BLUE.getColor());
        excludedTablesList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                excludedTablesListMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(excludedTablesList);

        jScrollPane3.setBorder(UiLib.createDefaultLineBorder());

        includedTablesList.setBackground(Config.Colors.APPLICATION_DEFAULT_BLUE.getColor());
        includedTablesList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                includedTablesListMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(includedTablesList);

        jLabel2.setFont(UiLib.getTitleFont());
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Backup Presets");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        reloadTablesButton.setText("Reload tables from database");
        reloadTablesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                reloadTablesButtonMousePressed(evt);
            }
        });

        javax.swing.GroupLayout tablePanelLayout = new javax.swing.GroupLayout(tablePanel);
        tablePanel.setLayout(tablePanelLayout);
        tablePanelLayout.setHorizontalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tablePanelLayout.createSequentialGroup()
                .addGroup(tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tablePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tablePanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tablePanelLayout.createSequentialGroup()
                                .addComponent(reloadTablesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(createBackupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tablePanelLayout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                                .addGap(87, 87, 87)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)))))
                .addGap(31, 31, 31))
        );
        tablePanelLayout.setVerticalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablePanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addGap(18, 18, 18)
                .addGroup(tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createBackupButton)
                    .addComponent(reloadTablesButton))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(presetPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(presetPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void onLoadPresetButtonClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onLoadPresetButtonClicked
        loadBackupPreset(new SimplePreset());
    }//GEN-LAST:event_onLoadPresetButtonClicked

    private void excludedTablesListMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_excludedTablesListMousePressed
        Rectangle listCellBounds = excludedTablesList.getCellBounds(excludedTablesList.getFirstVisibleIndex(), excludedTablesList.getLastVisibleIndex());
        if (null != listCellBounds && listCellBounds.contains(evt.getPoint())) {
            switchTable(SWITCH_TYPE.TO_RIGHT);
        } else {
            excludedTablesList.clearSelection();
        }
    }//GEN-LAST:event_excludedTablesListMousePressed

    private void includedTablesListMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_includedTablesListMousePressed
        Rectangle listCellBounds = includedTablesList.getCellBounds(includedTablesList.getFirstVisibleIndex(), includedTablesList.getLastVisibleIndex());
        if (null != listCellBounds && listCellBounds.contains(evt.getPoint())) {
            switchTable(SWITCH_TYPE.TO_LEFT);
        } else {
            includedTablesList.clearSelection();
        }
    }//GEN-LAST:event_includedTablesListMousePressed

    private void presetPickerPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_presetPickerPropertyChange
        loadPresetDescription();
    }//GEN-LAST:event_presetPickerPropertyChange

    private void reloadTablesButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reloadTablesButtonMousePressed
        loadData(true);
    }//GEN-LAST:event_reloadTablesButtonMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane backupPresetDescription;
    private javax.swing.JButton createBackupButton;
    private javax.swing.JList<String> excludedTablesList;
    private javax.swing.JList<String> includedTablesList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton loadPresetButton;
    private javax.swing.JPanel presetPanel;
    private javax.swing.JComboBox<BackupPreset> presetPicker;
    private javax.swing.JButton reloadTablesButton;
    private javax.swing.JPanel tablePanel;
    // End of variables declaration//GEN-END:variables

    /**
     * Method to do various fixes and style customizations to the GUI.
     */
    private void initComponentsExtra() {
        // Set various backgrounds to the default color of this application.
        this.setBackground(Config.Colors.APPLICATION_DEFAULT_BLUE.getColor());
        tablePanel.setBackground(Config.Colors.APPLICATION_DEFAULT_BLUE.getColor());
        presetPanel.setBackground(Config.Colors.APPLICATION_DEFAULT_BLUE.getColor());
        backupPresetDescription.setBackground(Config.Colors.APPLICATION_DEFAULT_BLUE.getColor());

        // Style the preset picker.
        // TODO: Actually style the preset picker...
        presetPicker.setBounds(new Rectangle(12, 9, 331, 26));
        presetPicker.setRenderer(new BackupPresetComboBoxRenderer());

        // Style the description pane.
        UiLib.setComponentPadding(backupPresetDescription, 5, 5, 5, 5);
        backupPresetDescription.setFont(UiLib.getDefaultFont());

        excludedTablesList.setCellRenderer(new DbTableListCellRenderer());
        includedTablesList.setCellRenderer(new DbTableListCellRenderer());
    }

    /**
     * Method to load all data from the model, into the view.
     */
    private void loadData(boolean hardReload) {

        this.tables = model.getTables(hardReload);

        DefaultListModel exModel = new DefaultListModel();
        DefaultListModel inModel = new DefaultListModel();

        if (null != this.tables) {
            for (String t : this.tables) {
                exModel.addElement(t);
            }
        }

        this.includedTablesList.setModel(inModel);
        this.excludedTablesList.setModel(exModel);
    }

    /**
     * Method to load all the backup presets into the view, and display them in
     * the combo box.
     */
    private void loadBackupPresetsIntoView() {
        this.presets = model.getBackupPresets();

        BackupPreset[] presetArray = new BackupPreset[this.presets.size()];

        for (int i = 0; i < this.presets.size(); i++) {
            presetArray[i] = this.presets.get(i);
        }

        presetPicker.setModel(new DefaultComboBoxModel(presetArray));
    }

    /**
     * Method to load a backup preset into the table lists.
     *
     * @param preset The preset that is to be loaded into the lists.
     */
    private void loadBackupPreset(BackupPreset preset) {

        String[] presetTables = preset.getSelectedTables();

        if (null == this.tables || presetTables == null) {
            return;
        }

        DefaultListModel<String> inModel = new DefaultListModel<>();
        DefaultListModel<String> exModel = new DefaultListModel<>();

        if (preset.getPresetType().equals(PresetType.INCLUDE_SELECTED)) {
            for (String table : this.tables) {
                if (Arrays.asList(presetTables).contains(table)) {
                    inModel.addElement(table);
                } else {
                    exModel.addElement(table);
                }
            }
        } else if (preset.getPresetType().equals(PresetType.EXCLUDE_SELECTED)) {
            for (String table : this.tables) {
                if (Arrays.asList(presetTables).contains(table)) {
                    exModel.addElement(table);
                } else {
                    inModel.addElement(table);
                }
            }
        }

        this.includedTablesList.setModel(inModel);
        this.excludedTablesList.setModel(exModel);
    }

    /**
     * Method to set the preset description field. This is mainly used when the
     * current preset selection changes.
     */
    private void loadPresetDescription() {
        BackupPreset preset = getSelectedPreset();
        if (null != preset) {
            backupPresetDescription.setText(preset.getDescription());
        }
    }

    /**
     * Getter for the current selected preset in the preset picker.
     *
     * @return A BackupPreset object, reflecting the currently selected preset.
     */
    private BackupPreset getSelectedPreset() {
        DefaultComboBoxModel<BackupPreset> dataModel = (DefaultComboBoxModel<BackupPreset>) presetPicker.getModel();
        int selectedIndex = presetPicker.getSelectedIndex();

        if (selectedIndex >= 0) {
            return dataModel.getElementAt(selectedIndex);
        } else {
            return null;
        }
    }

    /**
     * Method to draw a separation line between the two main panels in this
     * view.
     *
     * @param graphics
     */
    @Override
    public void paint(Graphics graphics) {
        super.paint(graphics);
        // Draw a line.
        int margin = 0;
        Graphics2D graphicsNew = (Graphics2D) graphics;
        Line2D line = new Line2D.Float(presetPanel.getWidth(), 0 + margin, presetPanel.getWidth(), getHeight() - margin);
        graphicsNew.draw(line);
    }

    /**
     * Method to pass a table from one side to the other.
     *
     * @param switchType The direction of the change.
     */
    public void switchTable(SWITCH_TYPE switchType) {
        int leftIndex = excludedTablesList.getSelectedIndex();
        int rightIndex = includedTablesList.getSelectedIndex();
        DefaultListModel<String> leftModel = (DefaultListModel) excludedTablesList.getModel();
        DefaultListModel<String> rightModel = (DefaultListModel) includedTablesList.getModel();

        if (switchType.equals(SWITCH_TYPE.TO_RIGHT) && leftIndex >= 0) {
            String tableName = leftModel.getElementAt(leftIndex);

            rightModel.add(0, tableName);
            leftModel.removeElement(tableName);

            includedTablesList.setModel(rightModel);
            excludedTablesList.setModel(leftModel);

        } else if (switchType.equals(SWITCH_TYPE.TO_LEFT) && rightIndex >= 0) {
            String tableName = rightModel.getElementAt(rightIndex);

            leftModel.add(0, tableName);
            rightModel.removeElement(tableName);

            includedTablesList.setModel(rightModel);
            excludedTablesList.setModel(leftModel);
        }
    }
}
