/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import App.Controller;
import Backup.BackupPreset;
import Backup.BackupPreset.PresetType;
import Models.BackupModel;
import UiHelpers.BackupPresetComboBoxRenderer;
import UiHelpers.DbTableListCellRenderer;
import UiHelpers.UiLib;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Rectangle;
import java.awt.geom.Line2D;
import java.util.Arrays;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import App.Config;
import App.Logger;
import Backup.PostGresBackup;
import HelperClasses.Utils;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.util.ArrayList;
import java.util.regex.Pattern;
import javax.swing.JProgressBar;

public class BackupView extends javax.swing.JPanel {

    private final Controller controller;
    private final BackupModel model;
    private List<String> includedTables;
    private List<String> excludedTables;

    /**
     * Array consisting of all the tables in the database. The tables can be
     * loaded from the model.
     */
    private String[] tables;

    private List<BackupPreset> presets;

    public enum SWITCH_TYPE {
        TO_LEFT,
        TO_RIGHT;
    }

    /**
     * Creates new form BackupView
     *
     * @param controller The controller used to initialize this view.
     * @param model The model used to initialize this view.
     */
    public BackupView(Controller controller, BackupModel model) {
        initComponents();
        initComponentsExtra();
        this.controller = controller;
        this.model = model;
        loadData(false);
        loadBackupPresetsIntoView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        presetPanel = new javax.swing.JPanel();
        loadPresetButton = new javax.swing.JButton();
        presetPicker = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        backupPresetDescription = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        tablePanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        excludedTablesList = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        includedTablesList = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        btn_createBackup = new javax.swing.JButton();
        btn_includeAll = new javax.swing.JButton();
        btn_excludeAll = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        searchField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(15, 124, 160));
        setPreferredSize(new java.awt.Dimension(967, 479));

        loadPresetButton.setText("Load Preset");
        loadPresetButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onLoadPresetButtonClicked(evt);
            }
        });

        presetPicker.setBorder(null);
        presetPicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                presetPickerActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(null);

        backupPresetDescription.setEditable(false);
        backupPresetDescription.setBorder(null);
        jScrollPane1.setViewportView(backupPresetDescription);

        jLabel1.setFont(UiLib.getTitleFont());
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Backup Presets");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout presetPanelLayout = new javax.swing.GroupLayout(presetPanel);
        presetPanel.setLayout(presetPanelLayout);
        presetPanelLayout.setHorizontalGroup(
            presetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(presetPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(presetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(loadPresetButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(presetPicker, 0, 273, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(presetPanelLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        presetPanelLayout.setVerticalGroup(
            presetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, presetPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(presetPicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loadPresetButton)
                .addGap(44, 44, 44))
        );

        jScrollPane2.setBorder(UiLib.createDefaultLineBorder());
        jScrollPane2.setOpaque(false);

        excludedTablesList.setBackground(Config.Colors.APPLICATION_DEFAULT_BLUE.getColor());
        excludedTablesList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                excludedTablesListMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(excludedTablesList);

        jScrollPane3.setBorder(UiLib.createDefaultLineBorder());

        includedTablesList.setBackground(Config.Colors.APPLICATION_DEFAULT_BLUE.getColor());
        includedTablesList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                includedTablesListMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(includedTablesList);

        jLabel2.setFont(UiLib.getTitleFont());
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Selected Tables");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Included tables");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Excluded tables");

        jPanel1.setOpaque(false);

        btn_createBackup.setText("Create backup");
        btn_createBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_createBackupActionPerformed(evt);
            }
        });

        btn_includeAll.setText("Include all");
        btn_includeAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_includeAllActionPerformed(evt);
            }
        });

        btn_excludeAll.setText("Exclude all");
        btn_excludeAll.setMaximumSize(new java.awt.Dimension(95, 32));
        btn_excludeAll.setMinimumSize(new java.awt.Dimension(95, 32));
        btn_excludeAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excludeAllActionPerformed(evt);
            }
        });

        jButton1.setText("Reload tables from database");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_excludeAll, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_includeAll, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_createBackup, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_createBackup)
                    .addComponent(btn_includeAll)
                    .addComponent(btn_excludeAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        searchField.setText("Search...");
        searchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchFieldKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout tablePanelLayout = new javax.swing.GroupLayout(tablePanel);
        tablePanel.setLayout(tablePanelLayout);
        tablePanelLayout.setHorizontalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tablePanelLayout.createSequentialGroup()
                .addGroup(tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tablePanelLayout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tablePanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(tablePanelLayout.createSequentialGroup()
                                .addGroup(tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE))
                                .addGap(87, 87, 87)
                                .addGroup(tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(31, 31, 31))
        );
        tablePanelLayout.setVerticalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablePanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(presetPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(presetPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void onLoadPresetButtonClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onLoadPresetButtonClicked
        loadBackupPreset(getSelectedPreset());
    }//GEN-LAST:event_onLoadPresetButtonClicked

    private void excludedTablesListMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_excludedTablesListMousePressed
        Rectangle listCellBounds = excludedTablesList.getCellBounds(excludedTablesList.getFirstVisibleIndex(), excludedTablesList.getLastVisibleIndex());
        if (null != listCellBounds && listCellBounds.contains(evt.getPoint())) {
            switchTable(SWITCH_TYPE.TO_RIGHT);
        } else {
            excludedTablesList.clearSelection();
        }
    }//GEN-LAST:event_excludedTablesListMousePressed

    private void includedTablesListMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_includedTablesListMousePressed
        Rectangle listCellBounds = includedTablesList.getCellBounds(includedTablesList.getFirstVisibleIndex(), includedTablesList.getLastVisibleIndex());
        if (null != listCellBounds && listCellBounds.contains(evt.getPoint())) {
            switchTable(SWITCH_TYPE.TO_LEFT);
        } else {
            includedTablesList.clearSelection();
        }
    }//GEN-LAST:event_includedTablesListMousePressed

    private void btn_includeAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_includeAllActionPerformed
        if (this.tables.length <= 0) {
            loadData(true);
        }

        DefaultListModel exModel = new DefaultListModel();
        DefaultListModel inModel = new DefaultListModel();

        includedTables = new ArrayList<>();
        excludedTables = new ArrayList<>();

        if (null != this.tables) {
            for (String table : this.tables) {
                inModel.addElement(table);
                includedTables.add(table);
            }
        }

        this.includedTablesList.setModel(inModel);
        this.excludedTablesList.setModel(exModel);
    }//GEN-LAST:event_btn_includeAllActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        loadData(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void searchFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldKeyReleased
        filterLists(searchField.getText());
    }//GEN-LAST:event_searchFieldKeyReleased

    private void btn_excludeAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excludeAllActionPerformed
        if (this.tables.length <= 0) {
            loadData(true);
        }

        DefaultListModel exModel = new DefaultListModel();
        DefaultListModel inModel = new DefaultListModel();

        includedTables = new ArrayList<>();
        excludedTables = new ArrayList<>();

        if (null != this.tables) {
            for (String table : this.tables) {
                exModel.addElement(table);
                excludedTables.add(table);
            }
        }

        this.includedTablesList.setModel(inModel);
        this.excludedTablesList.setModel(exModel);
    }//GEN-LAST:event_btn_excludeAllActionPerformed

    private void btn_createBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_createBackupActionPerformed
        final String[] backupTables = new String[includedTables.size()];

        for (int i = 0; i < includedTables.size(); i++) {
            backupTables[i] = includedTables.get(i);
        }

        final double msPerPercent = (Config.getDouble("backup_ms_per_table") * includedTables.size()) / 100;
        final JProgressBar bar = jProgressBar1;

        new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = 1; i <= 100; i++) {
                    bar.setValue(i);
                    try {
                        Thread.sleep((long) msPerPercent);
                    } catch (InterruptedException ex) {
                        Logger.warning("Progress-bar thread was interrupted:\n{0}", ex.getMessage());
                    }
                }
            }
        }).start();

        new Thread(new Runnable() {
            @Override
            public void run() {
                new PostGresBackup(backupTables).make();
            }
        }).start();
    }//GEN-LAST:event_btn_createBackupActionPerformed

    private void presetPickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_presetPickerActionPerformed
        System.out.println("Changed!");
        loadPresetDescription();
    }//GEN-LAST:event_presetPickerActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane backupPresetDescription;
    private javax.swing.JButton btn_createBackup;
    private javax.swing.JButton btn_excludeAll;
    private javax.swing.JButton btn_includeAll;
    private javax.swing.JList<String> excludedTablesList;
    private javax.swing.JList<String> includedTablesList;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton loadPresetButton;
    private javax.swing.JPanel presetPanel;
    private javax.swing.JComboBox<BackupPreset> presetPicker;
    private javax.swing.JTextField searchField;
    private javax.swing.JPanel tablePanel;
    // End of variables declaration//GEN-END:variables

    /**
     * Method to do various fixes and style customizations to the GUI.
     */
    private void initComponentsExtra() {
        // Set various backgrounds to the default color of this application.
        this.setBackground(Config.Colors.APPLICATION_DEFAULT_BLUE.getColor());
        tablePanel.setBackground(Config.Colors.APPLICATION_DEFAULT_BLUE.getColor());
        presetPanel.setBackground(Config.Colors.APPLICATION_DEFAULT_BLUE.getColor());
        backupPresetDescription.setBackground(Config.Colors.APPLICATION_DEFAULT_BLUE.getColor());

        // Style the preset picker.
        // TODO: Actually style the preset picker...
        presetPicker.setBounds(new Rectangle(12, 9, 331, 26));
        presetPicker.setRenderer(new BackupPresetComboBoxRenderer());

        // Style the description pane.
        UiLib.setComponentPadding(backupPresetDescription, 5, 5, 5, 5);
        backupPresetDescription.setFont(UiLib.getDefaultFont());

        excludedTablesList.setCellRenderer(new DbTableListCellRenderer());
        includedTablesList.setCellRenderer(new DbTableListCellRenderer());

        UiLib.styleTextField(searchField);
        searchField.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                if (searchField.getText().equals("Search...")) {
                    searchField.setText("");
                    searchField.setForeground(Config.Colors.FONT_COLOR_WHITE.getColor());
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (searchField.getText().isEmpty()) {
                    searchField.setForeground(Config.Colors.FONT_COLOR_DISABLED.getColor());
                    searchField.setText("Search...");
                }
            }
        });

        jProgressBar1.setStringPainted(true);
        jProgressBar1.setBorderPainted(false);
        jProgressBar1.setFont(UiLib.getTitleFont());
    }

    /**
     * Method to load all data from the model, into the view.
     */
    private void loadData(boolean hardReload) {

        this.tables = model.getTables(hardReload);

        DefaultListModel exModel = new DefaultListModel();
        DefaultListModel inModel = new DefaultListModel();

        includedTables = new ArrayList<>();
        excludedTables = new ArrayList<>();

        if (null != this.tables) {
            for (String table : this.tables) {
                exModel.addElement(table);
                excludedTables.add(table);
            }
        }

        this.includedTablesList.setModel(inModel);
        this.excludedTablesList.setModel(exModel);
    }

    /**
     * Method to load all the backup presets into the view, and display them in
     * the combo box.
     */
    private void loadBackupPresetsIntoView() {
        this.presets = model.getBackupPresets();

        BackupPreset[] presetArray = new BackupPreset[this.presets.size()];

        for (int i = 0; i < this.presets.size(); i++) {
            presetArray[i] = this.presets.get(i);
        }

        presetPicker.setModel(new DefaultComboBoxModel(presetArray));
    }

    /**
     * Method to load a backup preset into the table lists.
     *
     * @param preset The preset that is to be loaded into the lists.
     */
    private void loadBackupPreset(BackupPreset preset) {

        String[] presetTables = preset.getSelectedTables();

        if (null == this.tables || presetTables == null) {
            return;
        }

        DefaultListModel<String> inModel = new DefaultListModel<>();
        DefaultListModel<String> exModel = new DefaultListModel<>();

        includedTables = new ArrayList<>();
        excludedTables = new ArrayList<>();

        if (preset.getPresetType().equals(PresetType.INCLUDE_SELECTED)) {
            for (String table : this.tables) {
                if (Arrays.asList(presetTables).contains(table)) {
                    inModel.addElement(table);
                    includedTables.add(table);
                } else {
                    exModel.addElement(table);
                    excludedTables.add(table);
                }
            }
        } else if (preset.getPresetType().equals(PresetType.EXCLUDE_SELECTED)) {
            for (String table : this.tables) {
                if (Arrays.asList(presetTables).contains(table)) {
                    exModel.addElement(table);
                    excludedTables.add(table);
                } else {
                    inModel.addElement(table);
                    includedTables.add(table);
                }
            }
        }

        this.includedTablesList.setModel(inModel);
        this.excludedTablesList.setModel(exModel);
    }

    /**
     * Method to set the preset description field. This is mainly used when the
     * current preset selection changes.
     */
    private void loadPresetDescription() {
        BackupPreset preset = getSelectedPreset();
        if (null != preset) {
            backupPresetDescription.setText(preset.getDescription());
        }
    }

    /**
     * Getter for the current selected preset in the preset picker.
     *
     * @return A BackupPreset object, reflecting the currently selected preset.
     */
    private BackupPreset getSelectedPreset() {
        DefaultComboBoxModel<BackupPreset> dataModel = (DefaultComboBoxModel<BackupPreset>) presetPicker.getModel();
        int selectedIndex = presetPicker.getSelectedIndex();

        if (selectedIndex >= 0) {
            return dataModel.getElementAt(selectedIndex);
        } else {
            return null;
        }
    }

    /**
     * Method to filter the included and excluded table lists, in the view.
     * After filtering, only the tables that match the filter are shown in the
     * lists. Filtering is implemented with RegEx, and dots/stars are
     * automatically appended.
     *
     * @param filterString The string that is to be filtered on.
     */
    private void filterLists(String filterString) {

        DefaultListModel<String> inModel = new DefaultListModel<>();
        DefaultListModel<String> exModel = new DefaultListModel<>();

        String filter = ".*" + filterString + ".*";

        for (String table : excludedTables) {
            if (Utils.regExMatch(filter, table, Pattern.CASE_INSENSITIVE)) {
                exModel.add(exModel.getSize(), table);
            }
        }

        for (String table : includedTables) {
            if (Utils.regExMatch(filter, table, Pattern.CASE_INSENSITIVE)) {
                inModel.add(inModel.getSize(), table);
            }
        }

        includedTablesList.setModel(inModel);
        excludedTablesList.setModel(exModel);
    }

    /**
     * Method to draw a separation line between the two main panels in this
     * view.
     *
     * @param graphics
     */
    @Override
    public void paint(Graphics graphics) {
        super.paint(graphics);
        // Draw a line.
        int margin = 0;
        Graphics2D graphicsNew = (Graphics2D) graphics;
        Line2D line = new Line2D.Float(presetPanel.getWidth(), 0 + margin, presetPanel.getWidth(), getHeight() - margin);
        graphicsNew.draw(line);
    }

    /**
     * Method to pass a table from one side to the other.
     *
     * @param switchType The direction of the change.
     */
    public void switchTable(SWITCH_TYPE switchType) {
        int leftIndex = excludedTablesList.getSelectedIndex();
        int rightIndex = includedTablesList.getSelectedIndex();
        DefaultListModel<String> leftModel = (DefaultListModel) excludedTablesList.getModel();
        DefaultListModel<String> rightModel = (DefaultListModel) includedTablesList.getModel();

        if (switchType.equals(SWITCH_TYPE.TO_RIGHT) && leftIndex >= 0) {
            String tableName = leftModel.getElementAt(leftIndex);

            rightModel.add(0, tableName);
            leftModel.removeElement(tableName);

            includedTables.add(0, tableName);
            excludedTables.remove(tableName);

            includedTablesList.setModel(rightModel);
            excludedTablesList.setModel(leftModel);

        } else if (switchType.equals(SWITCH_TYPE.TO_LEFT) && rightIndex >= 0) {
            String tableName = rightModel.getElementAt(rightIndex);

            leftModel.add(0, tableName);
            rightModel.removeElement(tableName);

            excludedTables.add(0, tableName);
            includedTables.remove(tableName);

            includedTablesList.setModel(rightModel);
            excludedTablesList.setModel(leftModel);
        }
    }
}
