/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import sunetibargetool.Config;

/**
 *
 * @author niekv
 */
public class UserInterface extends javax.swing.JFrame {

    /**
     * Creates new form UI
     */
    public UserInterface() {
        initComponents();
        initExtra();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Suneti Barge Tool");
        setMinimumSize(new java.awt.Dimension(930, 465));
        setName("mainFrame"); // NOI18N
        setSize(new java.awt.Dimension(1100, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new UserInterface().setVisible(true);
            }
        });
    }

    private void initExtra() {
        // Set the icon in top left corner & taskbar.
        URL iconURL = getClass().getClassLoader().getResource("main_icon.png");
        ImageIcon icon = new ImageIcon(iconURL);
        setIconImage(icon.getImage());

        // Sets the layout to borderlayout, to easily place panels.
        setLayout(new BorderLayout());

        try {
            String laf = UIManager.getCrossPlatformLookAndFeelClassName();
            UIManager.setLookAndFeel(laf);
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException e) {
            System.out.println("Could not set custom LAF!");
        }

        // Sets the (preferred) size of this JFrame, can be adjusted later on.
        setPreferredSize(new Dimension(1100, 500));
        setSize(getPreferredSize());

        // Give some decent looks to the progress bars in this application.
        Color defaultGrey = Config.Colors.APPLICATION_DEFAULT_GREY.getColor();
        Color defaultBlue = Config.Colors.APPLICATION_DEFAULT_BLUE.getColor();

        UIManager.put("ProgressBar.background", defaultBlue);
        UIManager.put("ProgressBar.foreground", defaultGrey);
        UIManager.put("ProgressBar.selectionBackground", defaultGrey);
        UIManager.put("ProgressBar.selectionForeground", defaultBlue);
    }

    public void setPanel(JPanel panel, String place) {
        add(panel, place);
        revalidate();
        repaint();
    }

    public void removePanel(JPanel panel) {
        remove(panel);
        revalidate();
        repaint();
    }

    public void clearPanel(String place) {
        BorderLayout layout = (BorderLayout) getContentPane().getLayout();
        if (layout.getLayoutComponent(place) != null) {
            remove(layout.getLayoutComponent(place));
        }
        revalidate();
        repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
